include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  language:
    strict-casts: true
  exclude:
    - example/**/*.dart
linter:
  rules:
    - type_annotate_public_apis
    - void_checks
    - unnecessary_new