name: sqflite_gen
version: 0.0.1

homepage: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator
repository: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator
issue_tracker: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues

platforms:
  android:
  ios:
  macos:
  windows:
  linux:
  web:

description: Have you been turned into a problem with writing code for Http
  requests? This package can help. It has all of the Http and model codegen
  functionality you have been looking for.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.1
  path: ^1.9.0
  markdown: ">=5.0.0 <8.0.0"
  recase: ^4.1.0
  json_annotation: ^4.9.0
  universal_io: ^2.2.2
  dart_style: ^2.3.6
  code_builder: ^4.10.0
  http: ^1.2.2
  yaml: ^3.1.2
  sqlparser: ">=0.37.1 <0.39.0"
  fpdart: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  remove_from_coverage: ^2.0.0
  lints: ^4.0.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
