name: sqflite_gen
version: 0.1.0

homepage: https://github.com/olliaustor/sqflite_gen
repository: https://github.com/olliaustor/sqflite_gen
issue_tracker: https://github.com/olliaustor/sqflite_gen/issues

platforms:
  android:
  ios:
  macos:
  windows:
  linux:
  web:

description: Tired of writing boilerplate code for accessing sqlite database using sqflite? This package can help. 
  It has all of the table specific provider and model code generation functionality you have been looking for.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.1
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  fpdart: ^1.1.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  markdown: ">=5.0.0 <8.0.0"
  path: ^1.9.0
  recase: ^4.1.0
  sqlparser: ^0.37.1
  universal_io: ^2.2.2
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  lints: ^4.0.0
  mocktail: ^1.0.4
  remove_from_coverage: ^2.0.0
  test: ^1.25.8
  very_good_analysis: ^6.0.0
