name: sqflite_gen
version: 0.1.1

homepage: https://github.com/olliaustor/sqflite_gen
repository: https://github.com/olliaustor/sqflite_gen
issue_tracker: https://github.com/olliaustor/sqflite_gen/issues

platforms:
  android:
  ios:
  macos:
  windows:
  linux:
  web:

description: Table specific provider and model code generation functionality for sqlite.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.2
  code_builder: ^4.10.1
  dart_style: ^3.0.1
  fpdart: ^1.1.1
  http: ^1.3.0
  json_annotation: ^4.9.0
  markdown: ^7.3.0
  path: ^1.9.1
  recase: ^4.1.0
  sqlparser: ^0.41.0
  universal_io: ^2.2.2
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  lints: ^5.1.1
  mocktail: ^1.0.4
  remove_from_coverage: ^2.0.0
  test: ^1.25.15
  very_good_analysis: ^7.0.0
